[package]
name = "day6"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.6"
clap = { version = "4.3", features = ["derive"] } # For command-line arguments
rayon = "1.8" # For parallel processing
